### ISSUE TITLE
Explaining mailing lists

### ISSUE THREAD

**Issue by jrlevine** [ietf-wg-emailcore/emailcore#61] opened 2022-02-17 18:14 UTC
Sec 3.4.2 tries to explain aliases and mailing lists. While I think there is a useful distinction between lists that rewrite the bounce address and aliases that don't, most of the rest of the section seems out of date. Nobody I know cares about "exploders" any more; if there are 10 people at site x, as often as not one sends ten copies of the message and nobody cares.

The bit in 3.4.2 about not changing the header I think really means not rewriting existing headers, i.e., don't treat it as submission. Adding more headers seems harmless.

**Comment by aamelnikov** [comment] 2022-05-19 11:43
Looks like a duplicate of https://github.com/ietf-wg-emailcore/emailcore/issues/12

**Comment by aamelnikov** [comment] 2022-08-22 10:43
Ticket #12 got closed with "no change", closing this one as well.

**Closed as completed by aamelnikov** 2022-08-22 10:43 UTC
Labels: duplicate, component_smtp
