### ISSUE TITLE
Required 8BITMIME

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#64] opened 2022-03-06 02:38 UTC
Copying from Appendix G.16 of draft-ietf-emailcore-rfc5321bis-05 (preserved in subsequent versions):

There was extensive discussion on the mailing list in October 2021   about messages with and without 8-bit (i.e., octets with the leading  on) content and a tentative conclusion that support for 8BITMIME   should be required.  If that is the WG's conclusion, we need to figure out what to say and where to say it.

Since this has not been resolved through draft-ietf-emailcore-rfc5321bis-10, creating a ticket.

**Comment by klensin** [comment] 2022-03-06 04:57
Note that a requirement for 8BITMIME has been incorporated into Section 2.4 of draft-ietf-emailcore-as-04 so, if a determination has been made that it represents WG consensus (or there are no objections), this ticket can be immediately closed.

**Comment by aamelnikov** [comment] 2022-05-19 11:52
I think this is a duplicate (a part of) https://github.com/ietf-wg-emailcore/emailcore/issues/40

**Comment by aamelnikov** [comment] 2022-07-04 14:00
Closing as a duplicate of #40, which is more generic.

**Closed as completed by aamelnikov** 2022-07-04 14:00 UTC
Labels: duplicate, component_email-applicability-statement, component_smtp
